### ISSUE TITLE
Move more functions into flowz

### ISSUE THREAD

**Issue by PatrickDRusk** [ethanrowe/flowz#10] opened 2016-06-08 21:10 UTC
Moving additional "known to work" functions into flowz, including relevant API changes.

The unit tests and further documentation for this functions will move shortly thereafter.

**Comment by ethanrowe** [comment] 2016-06-13 20:02
@PatrickDRusk do you think this should be going into the next release?  I was aiming for Tuesday afternoon or Wednesday morning.

**Comment by PatrickDRusk** [comment] 2016-06-13 20:13
Yes. Though there are not yet unit tests for the functions, the script that I have been refactoring along the way continues to function properly with those moved/renamed functions.

**Comment by ethanrowe** [comment] 2016-06-13 23:34
Okay, I'm marking this as done, then, since it's integrated into ``develop`` for the next release as intended.

**Closed by ethanrowe** 2016-06-13 23:34 UTC
